planner_type = "Waypoints"

waypoints_x = [1100, 1100, 1000, 1000]
waypoints_y = [1000, 1100, 1100, 1000]
waypoints_z = [100, 100, 100, 100]

yoyo = false

target_horizontal_velocity = 1.0
target_vertical_velocity = 1.0
target_rotational_velocity = 0.0872665