planner_type = "Waypoints"

waypoints_x = [5000, 5000, 5000, 5000]
waypoints_y = [5000, 10000, 10000, 5000]
waypoints_z = [1000, 100, 100, 100]

yoyo = false

target_horizontal_velocity = 1.0
target_vertical_velocity = 1.0
target_rotational_velocity = 0.01745329