planner_type = "NonLinearFilterHoming"


pattern_size = 200
follow_heading_replan_time = 0
restart_threshold = 0.2
use_dvl = true

operation_region.min.x = -150000
operation_region.min.y = -150000
operation_region.min.z = 0
operation_region.max.x = 150000
operation_region.max.y = 150000
operation_region.max.z = 5000

target_horizontal_velocity = 1.0
target_rotational_velocity = 0.0872665
