planner_type = "NestedBin"

spiral_spacing = 5000
initial_spacing = 4000
final_spacing = 200
fail_time = 5011200

yoyo_during_spiral = true
yoyo_min_depth = 100
yoyo_max_depth = 2000
target_vertical_velocity_spiral = 1
target_vertical_velocity_gd_yoyo = 0.1
target_horizontal_velocity = 1
target_rotational_velocity = 0.349066

detection_threshold = 2.0

target_data = "plume"
lawnmower_data_range = 10

start_location.x = 16761.2930882
start_location.y = 25307.4428283
start_location.z = 0

has_sim_target = true
sim_target.x = 0
sim_target.y = 0
sim_target.z = 0

operation_region.min.x = -150000
operation_region.min.y = -150000
operation_region.min.z = 0
operation_region.max.x = 150000
operation_region.max.y = 150000
operation_region.max.z = 5000

sonar_depth_enabled = true
sonar_data = "sonar_depth"

gradient_descent_time = 60

depth_buffer = 15
seafloor_buffer = 20
yo_gradient_threshold = -0.01

yoyo_replan_time = 10
